### ISSUE TITLE
latest version is broken on arm

### ISSUE THREAD

**Issue by jasongdove** [linuxserver/docker-ffmpeg#19] opened 2022-06-26 22:37 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

ffmpeg prints its version and configuration

## Current Behavior

```
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/ffmpeg)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/ffmpeg)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libass.so.9)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvidstab.so.1.1)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvpx.so.6)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libmp3lame.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libopenjp2.so.7)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libopus.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvorbis.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libx264.so.164)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libx265.so.188)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libxvidcore.so.4)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libkvazaar.so.6)
```

## Steps to Reproduce

1. ```docker run --rm lscr.io/linuxserver/ffmpeg:latest```

## Environment
**OS:** Armbian Bullseye on Odroid N2+
**CPU architecture:** arm32, arm64
**How docker service was installed:** official docker repo

## Command used to create docker container (run/create/compose/screenshot)

```docker run --rm lscr.io/linuxserver/ffmpeg:latest```

## Docker logs

```
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/ffmpeg)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/ffmpeg)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libass.so.9)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvidstab.so.1.1)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvpx.so.6)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libmp3lame.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libopenjp2.so.7)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libopus.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libvorbis.so.0)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libx264.so.164)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libx265.so.188)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libxvidcore.so.4)
/usr/local/bin/ffmpeg: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/lib/libkvazaar.so.6)
```

**Comment by ajaykarthikr** [comment] 2022-07-22 06:54
@jasongdove Hey, I am also getting this same issue. Did you figure out anything?

**Comment by jasongdove** [comment] 2022-07-25 10:40
Unfortunately no, I haven't dug into this at all. I just pinned this dependency on the previous version so it doesn't break my projects.

**Comment by thespad** [comment] 2022-07-25 11:14
Looks like an issue caused by the rebase to Focal which ships with glibc 2.31 - I didn't test on arm so it might be arch-specific but the ffmpeg build is done against Focal too so I'm not sure why there's a mismatch.

I'll dig into it when I get a chance.

**Comment by thespad** [comment] 2022-07-25 11:38
Somehow when we rebased to Focal we missed the arm Dockerfiles so the binaries are being built against Focal and then trying to run on Bionic, hence the errors. Linked PR should fix it once merged - apologies.

**Closed** 2022-07-25 13:17 UTC
